### ISSUE TITLE
Порядок записи кода

### ISSUE THREAD

**Issue by TopGun-DICD** [lapinuelle/PetriLogicSimulatorProject#1]
Симулятор вылетает с ошибкой, если в коде секция initial идёт до описания компонентов.

Прикладываю пример файла, на котором можно посмотреть результат.
Если перенести секцию initial после описания вентилей, то всё работает.
[2bit_shift_REG_hier_flat_v2.txt](https://github.com/lapinuelle/PetriLogicSimulatorProject/files/106296/2bit_shift_REG_hier_flat_v2.txt)

**Comment by lapinuelle** [comment]
Я даже знаю, почему так. Если взглянуть на пример, то там порты объявляются как раз после блока initial. Данный баг уберется сам собой, если в объявлении модуля будут в скобках указаны порты

**Comment by TopGun-DICD** [comment]
В объявлении модуля порты присутствуют.
Они присутствуют и в списке портов модуля, и в описании input и output.

**Comment by lapinuelle** [comment]
А, кхм, видимо, не тот файл смотрел. Буду дебажить

**Comment by lapinuelle** [comment]
всё, я нашёл, в чём корень баги с initial. В ридере мы добавляем новое событие функцией addEvent, которая принимает в качестве аргумента указатель на net. Этот самый указатель, чтоб ей передать, вытаскивается из базы пинов функцией returnNet. Когда гейты идут до initial, все пины записываются в вектор и хранятся там. Если initial идёт до них, до и пинов в векторе нет => их неоткуда выдрать и передать в addEvent.

**Comment by lapinuelle** [comment]
Исправлено заменой метода addNet на returnNet.
