### ISSUE TITLE
Виснет симулятор

### ISSUE THREAD

**Issue by TopGun-DICD** [lapinuelle/PetriLogicSimulatorProject#12]
[2bit_shift_REG_hier.txt](https://github.com/lapinuelle/PetriLogicSimulatorProject/files/1372664/2bit_shift_REG_hier.txt)

**Comment by lapinuelle** [comment]
Проблема заключается в том, что на определённом этапе моделирования происходит закольцовывание, и число повторений одной итерации моделирования доходит до 500 (наше ограничение)

**Comment by lapinuelle** [comment]
А происходит это из-за кривой реализации чтения поведенческих модулей. Недоглядел где-то.

**Comment by lapinuelle** [comment]
Всё глубже закапываюсь в корни проблемы, пока так и не понял, где именно косяк

**Comment by lapinuelle** [comment]
Нашёл в чём косяк. Описывать инвертор через always @in, где in - его вход, было не самой лучшей идеей. В процессе моделирования возникает ситуация, когда состояние на входе не меняется, и вентиль не срабатывает. А должен, но не может, т.к. реализован он для срабатывания по фронту/срезу. Соответственно, нужно либо переписывать инвертор в виде

always
  begin
    if(in == 1)
      out = 0;
    if(in == 0)
      out = 1;
  end

либо не пытаться изобретать велосипед и сконцентрироваться на реализации posedge и negedge для запиливания сложных процедурных конструкций (триггеров, например).

Однако, в первом случае возникает необходимость отличать такие always от генераторов (#time), поскольку отсутствует ключевой токен '@'.
