### ISSUE TITLE
GateDumper bug

### ISSUE THREAD

**Issue by TopGun-DICD** [lapinuelle/PetriLogicSimulatorProject#27]
GateDumper.cpp, строка 173
Функция gdumper.finish() вызывается до того, как это действительно необходимо.
После вызова этой функции симулятор переходит на новую итерацию и снова пытается дампить.

В GateDumper::finish() лучше сделать всё как надо, то есть закрывая файл обнулить и указатель.

void GateDumper::finish()
{
  fclose(dumpFile);
  dumpFile = nullptr;
}

**Comment by lapinuelle** [comment]
Займусь на неделе, вероятно, ближе к среде

**Comment by lapinuelle** [comment]
Fixed
