### ISSUE TITLE
Работа netlistreader'а

### ISSUE THREAD

**Issue by TopGun-DICD** [lapinuelle/PetriLogicSimulatorProject#5]
В данный момент в main перед чтением схемы иерархический нетлист приводится к плоскому, который затем не удаляется (файл с именем <исходное_имя>_flat.v)
Но главное - имя выходного файла соответствует имени плоского нетлиста, а не исходного. И это баг.

**Comment by lapinuelle** [comment]
То что он не удаляется - это скорее не баг, а отладочная фича. Это было нужно, когда доводили до ума перевод в плоский нетлист.

**Comment by TopGun-DICD** [comment]
Думаю, эту заметку можно уже удалить, с чтением иерархии всё стало лучше.
