### ISSUE TITLE
Ошибка при чтении комментариев

### ISSUE THREAD

**Issue by TopGun-DICD** [lapinuelle/PetriLogicSimulatorProject#6]
Выходим за рамки массива при чтении комментариев.
Где-то налажал с индексами.
[adder.txt](https://github.com/lapinuelle/PetriLogicSimulatorProject/files/531195/adder.txt)

**Comment by lapinuelle** [comment]
Ошибка кроется в читалке иерархии, ковыряюсь

**Comment by lapinuelle** [comment]
Тут даже не читалка иерархии, а метод Tokenize. Вкостылил в него замену всех комментариев на "" через regex_replace, больше не вываливается. Комментарии же нам не нужны в самом моделировании, значит, при чтении нетлиста, а также подгоне иерархии в плоский вид, просто избавляемся от них
