### ISSUE TITLE
Несколько присвоений в одно время в initial

### ISSUE THREAD

**Issue by TopGun-DICD** [lapinuelle/PetriLogicSimulatorProject#7]
Наблюдается косяк, связанный, скорее всего, с чтением.

Разные результаты моделирования для 
initial
begin
    #0    Cin=0;
    #0    A=0;
    #0    B=0;
    #10   A=1;

и для 
initial 
begin
    #0    Cin=0;
            A=0;
            B=0;
            A=1;

Что в первом, что во втором случае результаты моделирования неправильные.

[adder_01.txt](https://github.com/lapinuelle/PetriLogicSimulatorProject/files/531200/adder_01.txt)
[adder_02.txt](https://github.com/lapinuelle/PetriLogicSimulatorProject/files/531203/adder_02.txt)

**Comment by lapinuelle** [comment]
Исправлено
