### ISSUE TITLE
Косяк $finish

### ISSUE THREAD

**Issue by TopGun-DICD** [lapinuelle/PetriLogicSimulatorProject#9]
При чтении такого файла возникает косяк: если указан в initial момент времени, но никакого события нет (нет присвоения сигнала), то в список выводимых переменных попадает $finish.

[inv.txt](https://github.com/lapinuelle/PetriLogicSimulatorProject/files/1372650/inv.txt)

**Comment by lapinuelle** [comment]
А как себя Icarus ведёт в таком случае?

**Comment by TopGun-DICD** [comment]
Icarus , само собой, ведёт себя правильно :)
Я смотрю, работает нормально теперь. Фикс чтения присвоений в один момент времени починил и чтение $finish.
Закрываю.
